// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Demo.proto

package com.redteamobile.matrix.pb;

/**
 * Protobuf type {@code BundleDetail}
 */
public  final class BundleDetail extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:BundleDetail)
    BundleDetailOrBuilder {
  // Use BundleDetail.newBuilder() to construct.
  private BundleDetail(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BundleDetail() {
    id_ = 0;
    type_ = "";
    status_ = 0;
    location_ = "";
    dataVolume_ = 0;
    dailyLimit_ = 0;
    duration_ = 0;
    getResourceMethod_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private BundleDetail(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            id_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            type_ = s;
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            status_ = rawValue;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            location_ = s;
            break;
          }
          case 40: {

            dataVolume_ = input.readInt32();
            break;
          }
          case 48: {

            dailyLimit_ = input.readInt32();
            break;
          }
          case 56: {

            duration_ = input.readInt32();
            break;
          }
          case 64: {

            getResourceMethod_ = input.readInt32();
            break;
          }
          case 74: {
            com.redteamobile.matrix.pb.BundleDetail.Network.Builder subBuilder = null;
            if (network_ != null) {
              subBuilder = network_.toBuilder();
            }
            network_ = input.readMessage(com.redteamobile.matrix.pb.BundleDetail.Network.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(network_);
              network_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.redteamobile.matrix.pb.Demo.internal_static_BundleDetail_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.redteamobile.matrix.pb.Demo.internal_static_BundleDetail_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.redteamobile.matrix.pb.BundleDetail.class, com.redteamobile.matrix.pb.BundleDetail.Builder.class);
  }

  /**
   * Protobuf enum {@code BundleDetail.BundleStatus}
   */
  public enum BundleStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ACTIVE = 0;</code>
     */
    ACTIVE(0),
    /**
     * <code>INACTIVE = 1;</code>
     */
    INACTIVE(1),
    /**
     * <code>EXPIRED = 2;</code>
     */
    EXPIRED(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>ACTIVE = 0;</code>
     */
    public static final int ACTIVE_VALUE = 0;
    /**
     * <code>INACTIVE = 1;</code>
     */
    public static final int INACTIVE_VALUE = 1;
    /**
     * <code>EXPIRED = 2;</code>
     */
    public static final int EXPIRED_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static BundleStatus valueOf(int value) {
      return forNumber(value);
    }

    public static BundleStatus forNumber(int value) {
      switch (value) {
        case 0: return ACTIVE;
        case 1: return INACTIVE;
        case 2: return EXPIRED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<BundleStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        BundleStatus> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<BundleStatus>() {
            public BundleStatus findValueByNumber(int number) {
              return BundleStatus.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.redteamobile.matrix.pb.BundleDetail.getDescriptor().getEnumTypes().get(0);
    }

    private static final BundleStatus[] VALUES = values();

    public static BundleStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private BundleStatus(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:BundleDetail.BundleStatus)
  }

  public interface NetworkOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BundleDetail.Network)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated string mcc = 1;</code>
     */
    java.util.List<java.lang.String>
        getMccList();
    /**
     * <code>repeated string mcc = 1;</code>
     */
    int getMccCount();
    /**
     * <code>repeated string mcc = 1;</code>
     */
    java.lang.String getMcc(int index);
    /**
     * <code>repeated string mcc = 1;</code>
     */
    com.google.protobuf.ByteString
        getMccBytes(int index);

    /**
     * <code>repeated string plmn = 2;</code>
     */
    java.util.List<java.lang.String>
        getPlmnList();
    /**
     * <code>repeated string plmn = 2;</code>
     */
    int getPlmnCount();
    /**
     * <code>repeated string plmn = 2;</code>
     */
    java.lang.String getPlmn(int index);
    /**
     * <code>repeated string plmn = 2;</code>
     */
    com.google.protobuf.ByteString
        getPlmnBytes(int index);

    /**
     * <code>repeated string fplmn = 3;</code>
     */
    java.util.List<java.lang.String>
        getFplmnList();
    /**
     * <code>repeated string fplmn = 3;</code>
     */
    int getFplmnCount();
    /**
     * <code>repeated string fplmn = 3;</code>
     */
    java.lang.String getFplmn(int index);
    /**
     * <code>repeated string fplmn = 3;</code>
     */
    com.google.protobuf.ByteString
        getFplmnBytes(int index);
  }
  /**
   * Protobuf type {@code BundleDetail.Network}
   */
  public  static final class Network extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:BundleDetail.Network)
      NetworkOrBuilder {
    // Use Network.newBuilder() to construct.
    private Network(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Network() {
      mcc_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      plmn_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      fplmn_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Network(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                mcc_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              mcc_.add(s);
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                plmn_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              plmn_.add(s);
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                fplmn_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              fplmn_.add(s);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          mcc_ = mcc_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          plmn_ = plmn_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          fplmn_ = fplmn_.getUnmodifiableView();
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.redteamobile.matrix.pb.Demo.internal_static_BundleDetail_Network_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.redteamobile.matrix.pb.Demo.internal_static_BundleDetail_Network_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.redteamobile.matrix.pb.BundleDetail.Network.class, com.redteamobile.matrix.pb.BundleDetail.Network.Builder.class);
    }

    public static final int MCC_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList mcc_;
    /**
     * <code>repeated string mcc = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getMccList() {
      return mcc_;
    }
    /**
     * <code>repeated string mcc = 1;</code>
     */
    public int getMccCount() {
      return mcc_.size();
    }
    /**
     * <code>repeated string mcc = 1;</code>
     */
    public java.lang.String getMcc(int index) {
      return mcc_.get(index);
    }
    /**
     * <code>repeated string mcc = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMccBytes(int index) {
      return mcc_.getByteString(index);
    }

    public static final int PLMN_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList plmn_;
    /**
     * <code>repeated string plmn = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getPlmnList() {
      return plmn_;
    }
    /**
     * <code>repeated string plmn = 2;</code>
     */
    public int getPlmnCount() {
      return plmn_.size();
    }
    /**
     * <code>repeated string plmn = 2;</code>
     */
    public java.lang.String getPlmn(int index) {
      return plmn_.get(index);
    }
    /**
     * <code>repeated string plmn = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPlmnBytes(int index) {
      return plmn_.getByteString(index);
    }

    public static final int FPLMN_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList fplmn_;
    /**
     * <code>repeated string fplmn = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getFplmnList() {
      return fplmn_;
    }
    /**
     * <code>repeated string fplmn = 3;</code>
     */
    public int getFplmnCount() {
      return fplmn_.size();
    }
    /**
     * <code>repeated string fplmn = 3;</code>
     */
    public java.lang.String getFplmn(int index) {
      return fplmn_.get(index);
    }
    /**
     * <code>repeated string fplmn = 3;</code>
     */
    public com.google.protobuf.ByteString
        getFplmnBytes(int index) {
      return fplmn_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < mcc_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, mcc_.getRaw(i));
      }
      for (int i = 0; i < plmn_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, plmn_.getRaw(i));
      }
      for (int i = 0; i < fplmn_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, fplmn_.getRaw(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < mcc_.size(); i++) {
          dataSize += computeStringSizeNoTag(mcc_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getMccList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < plmn_.size(); i++) {
          dataSize += computeStringSizeNoTag(plmn_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getPlmnList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < fplmn_.size(); i++) {
          dataSize += computeStringSizeNoTag(fplmn_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getFplmnList().size();
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.redteamobile.matrix.pb.BundleDetail.Network)) {
        return super.equals(obj);
      }
      com.redteamobile.matrix.pb.BundleDetail.Network other = (com.redteamobile.matrix.pb.BundleDetail.Network) obj;

      boolean result = true;
      result = result && getMccList()
          .equals(other.getMccList());
      result = result && getPlmnList()
          .equals(other.getPlmnList());
      result = result && getFplmnList()
          .equals(other.getFplmnList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getMccCount() > 0) {
        hash = (37 * hash) + MCC_FIELD_NUMBER;
        hash = (53 * hash) + getMccList().hashCode();
      }
      if (getPlmnCount() > 0) {
        hash = (37 * hash) + PLMN_FIELD_NUMBER;
        hash = (53 * hash) + getPlmnList().hashCode();
      }
      if (getFplmnCount() > 0) {
        hash = (37 * hash) + FPLMN_FIELD_NUMBER;
        hash = (53 * hash) + getFplmnList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.redteamobile.matrix.pb.BundleDetail.Network parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.redteamobile.matrix.pb.BundleDetail.Network parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.redteamobile.matrix.pb.BundleDetail.Network parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.redteamobile.matrix.pb.BundleDetail.Network parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.redteamobile.matrix.pb.BundleDetail.Network parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.redteamobile.matrix.pb.BundleDetail.Network parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.redteamobile.matrix.pb.BundleDetail.Network parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.redteamobile.matrix.pb.BundleDetail.Network parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.redteamobile.matrix.pb.BundleDetail.Network parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.redteamobile.matrix.pb.BundleDetail.Network parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.redteamobile.matrix.pb.BundleDetail.Network prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BundleDetail.Network}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BundleDetail.Network)
        com.redteamobile.matrix.pb.BundleDetail.NetworkOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.redteamobile.matrix.pb.Demo.internal_static_BundleDetail_Network_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.redteamobile.matrix.pb.Demo.internal_static_BundleDetail_Network_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.redteamobile.matrix.pb.BundleDetail.Network.class, com.redteamobile.matrix.pb.BundleDetail.Network.Builder.class);
      }

      // Construct using com.redteamobile.matrix.pb.BundleDetail.Network.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        mcc_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        plmn_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        fplmn_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.redteamobile.matrix.pb.Demo.internal_static_BundleDetail_Network_descriptor;
      }

      public com.redteamobile.matrix.pb.BundleDetail.Network getDefaultInstanceForType() {
        return com.redteamobile.matrix.pb.BundleDetail.Network.getDefaultInstance();
      }

      public com.redteamobile.matrix.pb.BundleDetail.Network build() {
        com.redteamobile.matrix.pb.BundleDetail.Network result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.redteamobile.matrix.pb.BundleDetail.Network buildPartial() {
        com.redteamobile.matrix.pb.BundleDetail.Network result = new com.redteamobile.matrix.pb.BundleDetail.Network(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          mcc_ = mcc_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.mcc_ = mcc_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          plmn_ = plmn_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.plmn_ = plmn_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          fplmn_ = fplmn_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.fplmn_ = fplmn_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.redteamobile.matrix.pb.BundleDetail.Network) {
          return mergeFrom((com.redteamobile.matrix.pb.BundleDetail.Network)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.redteamobile.matrix.pb.BundleDetail.Network other) {
        if (other == com.redteamobile.matrix.pb.BundleDetail.Network.getDefaultInstance()) return this;
        if (!other.mcc_.isEmpty()) {
          if (mcc_.isEmpty()) {
            mcc_ = other.mcc_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMccIsMutable();
            mcc_.addAll(other.mcc_);
          }
          onChanged();
        }
        if (!other.plmn_.isEmpty()) {
          if (plmn_.isEmpty()) {
            plmn_ = other.plmn_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensurePlmnIsMutable();
            plmn_.addAll(other.plmn_);
          }
          onChanged();
        }
        if (!other.fplmn_.isEmpty()) {
          if (fplmn_.isEmpty()) {
            fplmn_ = other.fplmn_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureFplmnIsMutable();
            fplmn_.addAll(other.fplmn_);
          }
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.redteamobile.matrix.pb.BundleDetail.Network parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.redteamobile.matrix.pb.BundleDetail.Network) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList mcc_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureMccIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          mcc_ = new com.google.protobuf.LazyStringArrayList(mcc_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string mcc = 1;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getMccList() {
        return mcc_.getUnmodifiableView();
      }
      /**
       * <code>repeated string mcc = 1;</code>
       */
      public int getMccCount() {
        return mcc_.size();
      }
      /**
       * <code>repeated string mcc = 1;</code>
       */
      public java.lang.String getMcc(int index) {
        return mcc_.get(index);
      }
      /**
       * <code>repeated string mcc = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMccBytes(int index) {
        return mcc_.getByteString(index);
      }
      /**
       * <code>repeated string mcc = 1;</code>
       */
      public Builder setMcc(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMccIsMutable();
        mcc_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string mcc = 1;</code>
       */
      public Builder addMcc(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMccIsMutable();
        mcc_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string mcc = 1;</code>
       */
      public Builder addAllMcc(
          java.lang.Iterable<java.lang.String> values) {
        ensureMccIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, mcc_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string mcc = 1;</code>
       */
      public Builder clearMcc() {
        mcc_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string mcc = 1;</code>
       */
      public Builder addMccBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureMccIsMutable();
        mcc_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList plmn_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensurePlmnIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          plmn_ = new com.google.protobuf.LazyStringArrayList(plmn_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string plmn = 2;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getPlmnList() {
        return plmn_.getUnmodifiableView();
      }
      /**
       * <code>repeated string plmn = 2;</code>
       */
      public int getPlmnCount() {
        return plmn_.size();
      }
      /**
       * <code>repeated string plmn = 2;</code>
       */
      public java.lang.String getPlmn(int index) {
        return plmn_.get(index);
      }
      /**
       * <code>repeated string plmn = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPlmnBytes(int index) {
        return plmn_.getByteString(index);
      }
      /**
       * <code>repeated string plmn = 2;</code>
       */
      public Builder setPlmn(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePlmnIsMutable();
        plmn_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string plmn = 2;</code>
       */
      public Builder addPlmn(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePlmnIsMutable();
        plmn_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string plmn = 2;</code>
       */
      public Builder addAllPlmn(
          java.lang.Iterable<java.lang.String> values) {
        ensurePlmnIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, plmn_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string plmn = 2;</code>
       */
      public Builder clearPlmn() {
        plmn_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string plmn = 2;</code>
       */
      public Builder addPlmnBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensurePlmnIsMutable();
        plmn_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList fplmn_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureFplmnIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          fplmn_ = new com.google.protobuf.LazyStringArrayList(fplmn_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string fplmn = 3;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getFplmnList() {
        return fplmn_.getUnmodifiableView();
      }
      /**
       * <code>repeated string fplmn = 3;</code>
       */
      public int getFplmnCount() {
        return fplmn_.size();
      }
      /**
       * <code>repeated string fplmn = 3;</code>
       */
      public java.lang.String getFplmn(int index) {
        return fplmn_.get(index);
      }
      /**
       * <code>repeated string fplmn = 3;</code>
       */
      public com.google.protobuf.ByteString
          getFplmnBytes(int index) {
        return fplmn_.getByteString(index);
      }
      /**
       * <code>repeated string fplmn = 3;</code>
       */
      public Builder setFplmn(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFplmnIsMutable();
        fplmn_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string fplmn = 3;</code>
       */
      public Builder addFplmn(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFplmnIsMutable();
        fplmn_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string fplmn = 3;</code>
       */
      public Builder addAllFplmn(
          java.lang.Iterable<java.lang.String> values) {
        ensureFplmnIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, fplmn_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string fplmn = 3;</code>
       */
      public Builder clearFplmn() {
        fplmn_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string fplmn = 3;</code>
       */
      public Builder addFplmnBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureFplmnIsMutable();
        fplmn_.add(value);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:BundleDetail.Network)
    }

    // @@protoc_insertion_point(class_scope:BundleDetail.Network)
    private static final com.redteamobile.matrix.pb.BundleDetail.Network DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.redteamobile.matrix.pb.BundleDetail.Network();
    }

    public static com.redteamobile.matrix.pb.BundleDetail.Network getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Network>
        PARSER = new com.google.protobuf.AbstractParser<Network>() {
      public Network parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Network(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Network> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Network> getParserForType() {
      return PARSER;
    }

    public com.redteamobile.matrix.pb.BundleDetail.Network getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <code>optional int32 id = 1;</code>
   */
  public int getId() {
    return id_;
  }

  public static final int TYPE_FIELD_NUMBER = 2;
  private volatile java.lang.Object type_;
  /**
   * <code>optional string type = 2;</code>
   */
  public java.lang.String getType() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      type_ = s;
      return s;
    }
  }
  /**
   * <code>optional string type = 2;</code>
   */
  public com.google.protobuf.ByteString
      getTypeBytes() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      type_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATUS_FIELD_NUMBER = 3;
  private int status_;
  /**
   * <code>optional .BundleDetail.BundleStatus status = 3;</code>
   */
  public int getStatusValue() {
    return status_;
  }
  /**
   * <code>optional .BundleDetail.BundleStatus status = 3;</code>
   */
  public com.redteamobile.matrix.pb.BundleDetail.BundleStatus getStatus() {
    com.redteamobile.matrix.pb.BundleDetail.BundleStatus result = com.redteamobile.matrix.pb.BundleDetail.BundleStatus.valueOf(status_);
    return result == null ? com.redteamobile.matrix.pb.BundleDetail.BundleStatus.UNRECOGNIZED : result;
  }

  public static final int LOCATION_FIELD_NUMBER = 4;
  private volatile java.lang.Object location_;
  /**
   * <code>optional string location = 4;</code>
   */
  public java.lang.String getLocation() {
    java.lang.Object ref = location_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      location_ = s;
      return s;
    }
  }
  /**
   * <code>optional string location = 4;</code>
   */
  public com.google.protobuf.ByteString
      getLocationBytes() {
    java.lang.Object ref = location_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      location_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATA_VOLUME_FIELD_NUMBER = 5;
  private int dataVolume_;
  /**
   * <code>optional int32 data_volume = 5;</code>
   */
  public int getDataVolume() {
    return dataVolume_;
  }

  public static final int DAILY_LIMIT_FIELD_NUMBER = 6;
  private int dailyLimit_;
  /**
   * <code>optional int32 daily_limit = 6;</code>
   */
  public int getDailyLimit() {
    return dailyLimit_;
  }

  public static final int DURATION_FIELD_NUMBER = 7;
  private int duration_;
  /**
   * <code>optional int32 duration = 7;</code>
   */
  public int getDuration() {
    return duration_;
  }

  public static final int GET_RESOURCE_METHOD_FIELD_NUMBER = 8;
  private int getResourceMethod_;
  /**
   * <code>optional int32 get_resource_method = 8;</code>
   */
  public int getGetResourceMethod() {
    return getResourceMethod_;
  }

  public static final int NETWORK_FIELD_NUMBER = 9;
  private com.redteamobile.matrix.pb.BundleDetail.Network network_;
  /**
   * <code>optional .BundleDetail.Network network = 9;</code>
   */
  public boolean hasNetwork() {
    return network_ != null;
  }
  /**
   * <code>optional .BundleDetail.Network network = 9;</code>
   */
  public com.redteamobile.matrix.pb.BundleDetail.Network getNetwork() {
    return network_ == null ? com.redteamobile.matrix.pb.BundleDetail.Network.getDefaultInstance() : network_;
  }
  /**
   * <code>optional .BundleDetail.Network network = 9;</code>
   */
  public com.redteamobile.matrix.pb.BundleDetail.NetworkOrBuilder getNetworkOrBuilder() {
    return getNetwork();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    if (!getTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, type_);
    }
    if (status_ != com.redteamobile.matrix.pb.BundleDetail.BundleStatus.ACTIVE.getNumber()) {
      output.writeEnum(3, status_);
    }
    if (!getLocationBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, location_);
    }
    if (dataVolume_ != 0) {
      output.writeInt32(5, dataVolume_);
    }
    if (dailyLimit_ != 0) {
      output.writeInt32(6, dailyLimit_);
    }
    if (duration_ != 0) {
      output.writeInt32(7, duration_);
    }
    if (getResourceMethod_ != 0) {
      output.writeInt32(8, getResourceMethod_);
    }
    if (network_ != null) {
      output.writeMessage(9, getNetwork());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (!getTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, type_);
    }
    if (status_ != com.redteamobile.matrix.pb.BundleDetail.BundleStatus.ACTIVE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, status_);
    }
    if (!getLocationBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, location_);
    }
    if (dataVolume_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, dataVolume_);
    }
    if (dailyLimit_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, dailyLimit_);
    }
    if (duration_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, duration_);
    }
    if (getResourceMethod_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(8, getResourceMethod_);
    }
    if (network_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, getNetwork());
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.redteamobile.matrix.pb.BundleDetail)) {
      return super.equals(obj);
    }
    com.redteamobile.matrix.pb.BundleDetail other = (com.redteamobile.matrix.pb.BundleDetail) obj;

    boolean result = true;
    result = result && (getId()
        == other.getId());
    result = result && getType()
        .equals(other.getType());
    result = result && status_ == other.status_;
    result = result && getLocation()
        .equals(other.getLocation());
    result = result && (getDataVolume()
        == other.getDataVolume());
    result = result && (getDailyLimit()
        == other.getDailyLimit());
    result = result && (getDuration()
        == other.getDuration());
    result = result && (getGetResourceMethod()
        == other.getGetResourceMethod());
    result = result && (hasNetwork() == other.hasNetwork());
    if (hasNetwork()) {
      result = result && getNetwork()
          .equals(other.getNetwork());
    }
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getType().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    hash = (37 * hash) + LOCATION_FIELD_NUMBER;
    hash = (53 * hash) + getLocation().hashCode();
    hash = (37 * hash) + DATA_VOLUME_FIELD_NUMBER;
    hash = (53 * hash) + getDataVolume();
    hash = (37 * hash) + DAILY_LIMIT_FIELD_NUMBER;
    hash = (53 * hash) + getDailyLimit();
    hash = (37 * hash) + DURATION_FIELD_NUMBER;
    hash = (53 * hash) + getDuration();
    hash = (37 * hash) + GET_RESOURCE_METHOD_FIELD_NUMBER;
    hash = (53 * hash) + getGetResourceMethod();
    if (hasNetwork()) {
      hash = (37 * hash) + NETWORK_FIELD_NUMBER;
      hash = (53 * hash) + getNetwork().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.redteamobile.matrix.pb.BundleDetail parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.redteamobile.matrix.pb.BundleDetail parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.redteamobile.matrix.pb.BundleDetail parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.redteamobile.matrix.pb.BundleDetail parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.redteamobile.matrix.pb.BundleDetail parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.redteamobile.matrix.pb.BundleDetail parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.redteamobile.matrix.pb.BundleDetail parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.redteamobile.matrix.pb.BundleDetail parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.redteamobile.matrix.pb.BundleDetail parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.redteamobile.matrix.pb.BundleDetail parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.redteamobile.matrix.pb.BundleDetail prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code BundleDetail}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:BundleDetail)
      com.redteamobile.matrix.pb.BundleDetailOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.redteamobile.matrix.pb.Demo.internal_static_BundleDetail_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.redteamobile.matrix.pb.Demo.internal_static_BundleDetail_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.redteamobile.matrix.pb.BundleDetail.class, com.redteamobile.matrix.pb.BundleDetail.Builder.class);
    }

    // Construct using com.redteamobile.matrix.pb.BundleDetail.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      id_ = 0;

      type_ = "";

      status_ = 0;

      location_ = "";

      dataVolume_ = 0;

      dailyLimit_ = 0;

      duration_ = 0;

      getResourceMethod_ = 0;

      if (networkBuilder_ == null) {
        network_ = null;
      } else {
        network_ = null;
        networkBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.redteamobile.matrix.pb.Demo.internal_static_BundleDetail_descriptor;
    }

    public com.redteamobile.matrix.pb.BundleDetail getDefaultInstanceForType() {
      return com.redteamobile.matrix.pb.BundleDetail.getDefaultInstance();
    }

    public com.redteamobile.matrix.pb.BundleDetail build() {
      com.redteamobile.matrix.pb.BundleDetail result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.redteamobile.matrix.pb.BundleDetail buildPartial() {
      com.redteamobile.matrix.pb.BundleDetail result = new com.redteamobile.matrix.pb.BundleDetail(this);
      result.id_ = id_;
      result.type_ = type_;
      result.status_ = status_;
      result.location_ = location_;
      result.dataVolume_ = dataVolume_;
      result.dailyLimit_ = dailyLimit_;
      result.duration_ = duration_;
      result.getResourceMethod_ = getResourceMethod_;
      if (networkBuilder_ == null) {
        result.network_ = network_;
      } else {
        result.network_ = networkBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.redteamobile.matrix.pb.BundleDetail) {
        return mergeFrom((com.redteamobile.matrix.pb.BundleDetail)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.redteamobile.matrix.pb.BundleDetail other) {
      if (other == com.redteamobile.matrix.pb.BundleDetail.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (!other.getType().isEmpty()) {
        type_ = other.type_;
        onChanged();
      }
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      if (!other.getLocation().isEmpty()) {
        location_ = other.location_;
        onChanged();
      }
      if (other.getDataVolume() != 0) {
        setDataVolume(other.getDataVolume());
      }
      if (other.getDailyLimit() != 0) {
        setDailyLimit(other.getDailyLimit());
      }
      if (other.getDuration() != 0) {
        setDuration(other.getDuration());
      }
      if (other.getGetResourceMethod() != 0) {
        setGetResourceMethod(other.getGetResourceMethod());
      }
      if (other.hasNetwork()) {
        mergeNetwork(other.getNetwork());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.redteamobile.matrix.pb.BundleDetail parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.redteamobile.matrix.pb.BundleDetail) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int id_ ;
    /**
     * <code>optional int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }
    /**
     * <code>optional int32 id = 1;</code>
     */
    public Builder setId(int value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object type_ = "";
    /**
     * <code>optional string type = 2;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string type = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string type = 2;</code>
     */
    public Builder setType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string type = 2;</code>
     */
    public Builder clearType() {
      
      type_ = getDefaultInstance().getType();
      onChanged();
      return this;
    }
    /**
     * <code>optional string type = 2;</code>
     */
    public Builder setTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      type_ = value;
      onChanged();
      return this;
    }

    private int status_ = 0;
    /**
     * <code>optional .BundleDetail.BundleStatus status = 3;</code>
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>optional .BundleDetail.BundleStatus status = 3;</code>
     */
    public Builder setStatusValue(int value) {
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional .BundleDetail.BundleStatus status = 3;</code>
     */
    public com.redteamobile.matrix.pb.BundleDetail.BundleStatus getStatus() {
      com.redteamobile.matrix.pb.BundleDetail.BundleStatus result = com.redteamobile.matrix.pb.BundleDetail.BundleStatus.valueOf(status_);
      return result == null ? com.redteamobile.matrix.pb.BundleDetail.BundleStatus.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .BundleDetail.BundleStatus status = 3;</code>
     */
    public Builder setStatus(com.redteamobile.matrix.pb.BundleDetail.BundleStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .BundleDetail.BundleStatus status = 3;</code>
     */
    public Builder clearStatus() {
      
      status_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object location_ = "";
    /**
     * <code>optional string location = 4;</code>
     */
    public java.lang.String getLocation() {
      java.lang.Object ref = location_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        location_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string location = 4;</code>
     */
    public com.google.protobuf.ByteString
        getLocationBytes() {
      java.lang.Object ref = location_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        location_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string location = 4;</code>
     */
    public Builder setLocation(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      location_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string location = 4;</code>
     */
    public Builder clearLocation() {
      
      location_ = getDefaultInstance().getLocation();
      onChanged();
      return this;
    }
    /**
     * <code>optional string location = 4;</code>
     */
    public Builder setLocationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      location_ = value;
      onChanged();
      return this;
    }

    private int dataVolume_ ;
    /**
     * <code>optional int32 data_volume = 5;</code>
     */
    public int getDataVolume() {
      return dataVolume_;
    }
    /**
     * <code>optional int32 data_volume = 5;</code>
     */
    public Builder setDataVolume(int value) {
      
      dataVolume_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 data_volume = 5;</code>
     */
    public Builder clearDataVolume() {
      
      dataVolume_ = 0;
      onChanged();
      return this;
    }

    private int dailyLimit_ ;
    /**
     * <code>optional int32 daily_limit = 6;</code>
     */
    public int getDailyLimit() {
      return dailyLimit_;
    }
    /**
     * <code>optional int32 daily_limit = 6;</code>
     */
    public Builder setDailyLimit(int value) {
      
      dailyLimit_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 daily_limit = 6;</code>
     */
    public Builder clearDailyLimit() {
      
      dailyLimit_ = 0;
      onChanged();
      return this;
    }

    private int duration_ ;
    /**
     * <code>optional int32 duration = 7;</code>
     */
    public int getDuration() {
      return duration_;
    }
    /**
     * <code>optional int32 duration = 7;</code>
     */
    public Builder setDuration(int value) {
      
      duration_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 duration = 7;</code>
     */
    public Builder clearDuration() {
      
      duration_ = 0;
      onChanged();
      return this;
    }

    private int getResourceMethod_ ;
    /**
     * <code>optional int32 get_resource_method = 8;</code>
     */
    public int getGetResourceMethod() {
      return getResourceMethod_;
    }
    /**
     * <code>optional int32 get_resource_method = 8;</code>
     */
    public Builder setGetResourceMethod(int value) {
      
      getResourceMethod_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 get_resource_method = 8;</code>
     */
    public Builder clearGetResourceMethod() {
      
      getResourceMethod_ = 0;
      onChanged();
      return this;
    }

    private com.redteamobile.matrix.pb.BundleDetail.Network network_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.redteamobile.matrix.pb.BundleDetail.Network, com.redteamobile.matrix.pb.BundleDetail.Network.Builder, com.redteamobile.matrix.pb.BundleDetail.NetworkOrBuilder> networkBuilder_;
    /**
     * <code>optional .BundleDetail.Network network = 9;</code>
     */
    public boolean hasNetwork() {
      return networkBuilder_ != null || network_ != null;
    }
    /**
     * <code>optional .BundleDetail.Network network = 9;</code>
     */
    public com.redteamobile.matrix.pb.BundleDetail.Network getNetwork() {
      if (networkBuilder_ == null) {
        return network_ == null ? com.redteamobile.matrix.pb.BundleDetail.Network.getDefaultInstance() : network_;
      } else {
        return networkBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .BundleDetail.Network network = 9;</code>
     */
    public Builder setNetwork(com.redteamobile.matrix.pb.BundleDetail.Network value) {
      if (networkBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        network_ = value;
        onChanged();
      } else {
        networkBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .BundleDetail.Network network = 9;</code>
     */
    public Builder setNetwork(
        com.redteamobile.matrix.pb.BundleDetail.Network.Builder builderForValue) {
      if (networkBuilder_ == null) {
        network_ = builderForValue.build();
        onChanged();
      } else {
        networkBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .BundleDetail.Network network = 9;</code>
     */
    public Builder mergeNetwork(com.redteamobile.matrix.pb.BundleDetail.Network value) {
      if (networkBuilder_ == null) {
        if (network_ != null) {
          network_ =
            com.redteamobile.matrix.pb.BundleDetail.Network.newBuilder(network_).mergeFrom(value).buildPartial();
        } else {
          network_ = value;
        }
        onChanged();
      } else {
        networkBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .BundleDetail.Network network = 9;</code>
     */
    public Builder clearNetwork() {
      if (networkBuilder_ == null) {
        network_ = null;
        onChanged();
      } else {
        network_ = null;
        networkBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .BundleDetail.Network network = 9;</code>
     */
    public com.redteamobile.matrix.pb.BundleDetail.Network.Builder getNetworkBuilder() {
      
      onChanged();
      return getNetworkFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .BundleDetail.Network network = 9;</code>
     */
    public com.redteamobile.matrix.pb.BundleDetail.NetworkOrBuilder getNetworkOrBuilder() {
      if (networkBuilder_ != null) {
        return networkBuilder_.getMessageOrBuilder();
      } else {
        return network_ == null ?
            com.redteamobile.matrix.pb.BundleDetail.Network.getDefaultInstance() : network_;
      }
    }
    /**
     * <code>optional .BundleDetail.Network network = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.redteamobile.matrix.pb.BundleDetail.Network, com.redteamobile.matrix.pb.BundleDetail.Network.Builder, com.redteamobile.matrix.pb.BundleDetail.NetworkOrBuilder> 
        getNetworkFieldBuilder() {
      if (networkBuilder_ == null) {
        networkBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.redteamobile.matrix.pb.BundleDetail.Network, com.redteamobile.matrix.pb.BundleDetail.Network.Builder, com.redteamobile.matrix.pb.BundleDetail.NetworkOrBuilder>(
                getNetwork(),
                getParentForChildren(),
                isClean());
        network_ = null;
      }
      return networkBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:BundleDetail)
  }

  // @@protoc_insertion_point(class_scope:BundleDetail)
  private static final com.redteamobile.matrix.pb.BundleDetail DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.redteamobile.matrix.pb.BundleDetail();
  }

  public static com.redteamobile.matrix.pb.BundleDetail getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BundleDetail>
      PARSER = new com.google.protobuf.AbstractParser<BundleDetail>() {
    public BundleDetail parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new BundleDetail(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BundleDetail> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BundleDetail> getParserForType() {
    return PARSER;
  }

  public com.redteamobile.matrix.pb.BundleDetail getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

