// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Demo.proto

package com.redteamobile.matrix.pb;

public final class Demo {
  private Demo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Request2ListBundle_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Request2ListBundle_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Reply2ListBundle_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Reply2ListBundle_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BundleDetail_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BundleDetail_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BundleDetail_Network_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BundleDetail_Network_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nDemo.proto\032\031google/protobuf/any.proto\"" +
      "e\n\022Request2ListBundle\022\025\n\rmerchant_code\030\001" +
      " \001(\t\022*\n\006status\030\002 \001(\0162\032.BundleDetail.Bund" +
      "leStatus\022\014\n\004type\030\003 \001(\005\"C\n\020Reply2ListBund" +
      "le\022\017\n\007success\030\001 \001(\010\022\036\n\007bundles\030\002 \003(\0132\r.B" +
      "undleDetail\"\323\002\n\014BundleDetail\022\n\n\002id\030\001 \001(\005" +
      "\022\014\n\004type\030\002 \001(\t\022*\n\006status\030\003 \001(\0162\032.BundleD" +
      "etail.BundleStatus\022\020\n\010location\030\004 \001(\t\022\023\n\013" +
      "data_volume\030\005 \001(\005\022\023\n\013daily_limit\030\006 \001(\005\022\020" +
      "\n\010duration\030\007 \001(\005\022\033\n\023get_resource_method\030",
      "\010 \001(\005\022&\n\007network\030\t \001(\0132\025.BundleDetail.Ne" +
      "twork\0323\n\007Network\022\013\n\003mcc\030\001 \003(\t\022\014\n\004plmn\030\002 " +
      "\003(\t\022\r\n\005fplmn\030\003 \003(\t\"5\n\014BundleStatus\022\n\n\006AC" +
      "TIVE\020\000\022\014\n\010INACTIVE\020\001\022\013\n\007EXPIRED\020\0022F\n\014Gag" +
      "aProvider\0226\n\nListBundle\022\023.Request2ListBu" +
      "ndle\032\021.Reply2ListBundle\"\000B.\n\032com.redteam" +
      "obile.matrix.pbB\004DemoP\001\210\001\001\242\002\004Demob\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        }, assigner);
    internal_static_Request2ListBundle_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Request2ListBundle_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Request2ListBundle_descriptor,
        new java.lang.String[] { "MerchantCode", "Status", "Type", });
    internal_static_Reply2ListBundle_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Reply2ListBundle_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Reply2ListBundle_descriptor,
        new java.lang.String[] { "Success", "Bundles", });
    internal_static_BundleDetail_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_BundleDetail_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BundleDetail_descriptor,
        new java.lang.String[] { "Id", "Type", "Status", "Location", "DataVolume", "DailyLimit", "Duration", "GetResourceMethod", "Network", });
    internal_static_BundleDetail_Network_descriptor =
      internal_static_BundleDetail_descriptor.getNestedTypes().get(0);
    internal_static_BundleDetail_Network_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BundleDetail_Network_descriptor,
        new java.lang.String[] { "Mcc", "Plmn", "Fplmn", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
