// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Demo.proto

package com.redteamobile.matrix.pb;

public interface Reply2ListBundleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Reply2ListBundle)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bool success = 1;</code>
   */
  boolean getSuccess();

  /**
   * <code>repeated .BundleDetail bundles = 2;</code>
   */
  java.util.List<com.redteamobile.matrix.pb.BundleDetail> 
      getBundlesList();
  /**
   * <code>repeated .BundleDetail bundles = 2;</code>
   */
  com.redteamobile.matrix.pb.BundleDetail getBundles(int index);
  /**
   * <code>repeated .BundleDetail bundles = 2;</code>
   */
  int getBundlesCount();
  /**
   * <code>repeated .BundleDetail bundles = 2;</code>
   */
  java.util.List<? extends com.redteamobile.matrix.pb.BundleDetailOrBuilder> 
      getBundlesOrBuilderList();
  /**
   * <code>repeated .BundleDetail bundles = 2;</code>
   */
  com.redteamobile.matrix.pb.BundleDetailOrBuilder getBundlesOrBuilder(
      int index);
}
